version: 2.0.{build}
image:
  - Visual Studio 2022
environment:
  CLOUDSMITH_API_KEY:
    secure: gryxZxQ1A85JeBI+HHk8GQqY/RQ4y8Oq8kR3yZ2v9zmtnUEmtPmkARFfoypUO0K8
  matrix:
    - solution_name: win32/sdlpal.sln
      OPTIONS: /p:Platform=x64
build_script:
  - |-
    msbuild /nologo /m %solution_name% /p:Configuration=Release %OPTIONS%
before_build:
  - |-
    sed -i.bak 's#\.\./#https://github.com/sdlpal/#g' .gitmodules
    git submodule update --init --recursive
    pip install cloudsmith-cli
after_build:
  - |-
    if exist win32\Win32\Release\sdlpal.exe ( cd win32\Win32\Release & 7z a ..\..\..\sdlpal-win32-msvc.zip sdlpal.exe & cd ..\..\..\ )
  - ps: >-
      if([string]::IsNullOrEmpty($env:APPVEYOR_PULL_REQUEST_NUMBER)) {
              $COMMIT_DATE=((git show -s --format=%cs)|out-string).trim()
              $REV=((git rev-list --count HEAD)|out-string).trim()
              $COMMIT_ID=((git rev-parse --short HEAD)|out-string).trim()
              $VERSION="v$COMMIT_DATE-r$REV-g$COMMIT_ID"
              # upload artifacts
              if (Test-Path "sdlpal-win32-msvc.zip") { cloudsmith upload raw sdlpal/sdlpal "sdlpal-win32-msvc.zip" --version $VERSION --name win32-msvc --republish --tags "branch/$env:APPVEYOR_REPO_BRANCH"}
      }

deploy:
- provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: SDvpRENFzV+oGUJOpB3TtbzNu9pcQ6MAElcNRTXwFjagjsy5X70ylfO/1EAfdrRv

artifacts:
  - path: sdlpal-win32-msvc.zip
    name: Win32
